### ISSUE TITLE
Corrupt image attachments in 5.3 using cucumber integration

### ISSUE THREAD

**Issue by babantax** [reportportal/agent-java-cucumber4#66]
**Describe the bug**
Since we upgraded to RP version 5.3, our projects using **agent-java-cucumber4**(currently using 5.0.0-BETA-10) are logging corrupted screenshots.

**To Reproduce**
- Report Portal 5.3
- agent-java-cucumber4 (5.0.0-BETA-10)
![image](https://user-images.githubusercontent.com/52815118/91044013-e55c7e80-e614-11ea-8d4d-fbbb436da239.png)

See comparation between one screenshot properly saved (on the left) and the same saved after upgrade to 5.3 (on the right and not working) 

![image](https://user-images.githubusercontent.com/52815118/91044597-d4603d00-e615-11ea-80f1-018b5e2b1643.png)

**Comment by HardNorth** [comment]
@babantax BETA-10 is a pretty old agent. Have you tried newer one?

**Comment by babantax** [comment]
Yes but newer versions break our project because of depencencies problems. Was working fine until we updated to RP 5.3

**Comment by HardNorth** [comment]
@babantax what kind of problems? I can't help you in any case if you are unable to use the newest agent.

**Comment by HardNorth** [comment]
I'm 99% sure that the issue caused by an old agent version. Since it contains a bug of missed mime type for attachments. That means in most cases it will be transferred as a text and randomly damaged by servers. Whenever one of them decide to change the text encoding or line endings.

**Comment by babantax** [comment]
The problem is that newer versions of the agent make our project break. Depencies seem not compatibles.

**Comment by HardNorth** [comment]
@babantax To help you with the problem I need to know what's wrong. Could you be more specific? What exactly breaking?

**Comment by kristianadidas** [comment]
Hi @HardNorth ,
We tried up to  agent-java-cucumber4 5.0.0-BETA-12 using cucumber 4.8.1. 
But the issue @babantax reported is still reproducible after upgrading RP to 5.3.

Are you saying that those versions are not compatible and our only solution is to upgrade to newer version of cucumber and agents ? If so could you please tell us the minimum supported versions so that we can plan the work accordingly, doing a version change to cucumber 5 and newer agents requires some code refactoring in our framework.

Kind Regards,
Kris.

**Comment by HardNorth** [comment]
@kristianadidas You can still use cucumber 4, just newer agent. The fix was introduced in 5.0.0-BETA-13:
https://github.com/reportportal/agent-java-cucumber4/releases/tag/5.0.0-BETA-13

Just read the release notes.

**Comment by kristianadidas** [comment]
Thanks @HardNorth ,
There were some issues with cucumber 4.8.1 and going above agent BETA-12, i think it was mostly dependencies related.
I'll upgrade to BETA-15 and see if there are any issues.

**Comment by HardNorth** [comment]
@kristianadidas Again, could you be more specific, which kind of issues? I need details to help you.

**Comment by kristianadidas** [comment]
The error we got is 
` java.lang.NoClassDefFoundError: Could not initialize class com.epam.reportportal.cucumber.Utils`
But for now i'm  trying to figure out if its related to our setup or not, before i reach out for support. Still if you have any ideas all commets are welcome.

**Comment by HardNorth** [comment]
@kristianadidas Now I can catch a thread, at least. Do you include cucumber `cucumber-java` dependency by yourself or you rely on ours?

**Comment by kristianadidas** [comment]
Hi @HardNorth ,

We might have found a fix using the latest version BETA-15 and cucumber 4.8.1.
Last time we tried BETA-15 was not out yet and images still did not work.

We will test the setup now and if everything is working fine ill comment back here.

**Comment by HardNorth** [comment]
No response
